src/Major Assignment/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <displayFormat>AccNo-{00000}</displayFormat>
        <label>Account Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Major Assignment/objects/Transaction_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transaction Entries</relationshipLabel>
        <relationshipName>Transaction_Entries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Debit</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction Entry</label>
    <nameField>
        <displayFormat>TX-{00000}</displayFormat>
        <label>TX Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Major Assignment/classes/Records_PDF_Controller.cls
/**
*  Description     :  Download the PDF as per user require arguments
*
*  Created By      :  Jay Chand Yadav
*
*  Created Date    :  09/14/2022
*
*  Revision Logs   :  V1.0 - Created - jay Chand Yadav
**/
public with sharing class Records_PDF_Controller {
    public List<Transaction_Entry__c> transaction_Entry_List{get;set;}
    public String startDateString {set;get;}
    public String endDateString {set;get;}
    public Contact contact_Object{set;get;}

    public Records_PDF_Controller() {
        Apexpages.currentPage().getHeaders().put('content-disposition', 'attachment; filename=BankStatement.pdf');
    }

    public void recordPdf(){
        Id idOfContacts = ApexPages.currentPage().getParameters().get('id');
        String newStartDate = ApexPages.currentPage().getParameters().get('startdate');
        String newEndDate = ApexPages.currentPage().getParameters().get('enddate');

        Date startDate = Date.valueOf(newStartDate);
        Date endDate = Date.valueOf(newEndDate);

        System.debug('Startdate ==========> ' + startDate);
        System.debug('Enddate ============> ' + endDate);
        String stringStartDate = String.valueOf(date.newinstance(startDate.year(), startDate.month(), startDate.day()));
        String stringEndDate = String.valueOf(date.newinstance(endDate.year(), endDate.month(), endDate.day()));
        System.debug('------stringStartDate ' + stringStartDate);
        System.debug('-------stringEndDate---' + stringEndDate);
        Transaction_Entry_List  = [SELECT Id, Name, Transaction_Date__c, Amount__c,  Type__c, Status__c 
                                   FROM Transaction_Entry__c WHERE Contact__c = :idOfContacts 
                                   AND CreatedDate >= :startDate AND CreatedDate <= :endDate];
                                   System.debug('List Of Records'+Transaction_Entry_List);

        contact_Object = [SELECT Id, Title, Name , Email, Account_Number__c FROM Contact WHERE ID = :idOfContacts];
        System.debug('Contacts' +contact_Object);

        startDateString = newStartDate;
        endDateString = newEndDate;
    }

    
}