src/Major Assignment/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Limit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction Limit</label>
        <referenceTo>Transaction_Limit__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Major Assignment/objects/Transaction_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transaction Entries</relationshipLabel>
        <relationshipName>Transaction_Entries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Debit</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction Entry</label>
    <nameField>
        <displayFormat>TX-{00000}</displayFormat>
        <label>TX Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Major Assignment/objects/Transaction_Limit__c.object
<CustomObject>
    <fields>
        <fullName>Maximum_Debit_Allowed_per_Day__c</fullName>
        <label>Maximum Debit Allowed per Day</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Debit_Allowed_per_Month__c</fullName>
        <label>Maximum Debit Allowed per Month</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Debit_Allowed_per_Transaction__c</fullName>
        <label>Maximum Debit Allowed per Transaction</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Transactions_Allowed_per_Day__c</fullName>
        <label>Maximum Transactions Allowed per Day</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Transactions_Allowed_per_Month__c</fullName>
        <label>Maximum Transactions Allowed per Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Transaction Limit</label>
    <nameField>
        <label>Transaction Limits Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Limits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Major Assignment/classes/RetrieveTransactionEntriesRecordsTest.cls
/**
*  Description     :  Test Class for retrieve transaction records
*                     
*  Created By      :  Jay Chand Yadav
*
*  Created Date    :  09/20/2022
*
*  Revision Logs   :  V1.0 - Created - jay Chand Yadav
**/
@isTest(SeeAllData = false)
public class RetrieveTransactionEntriesRecordsTest {

    @TestSetup
    static void makeData(){
        
        Transaction_Limit__c limitOfSbiBank = new Transaction_Limit__c();
        limitOfSbiBank.name = 'SBI';
        limitOfSbiBank.Maximum_Debit_Allowed_per_Month__c = 900000;
        limitOfSbiBank.Maximum_Transactions_Allowed_per_Month__c = 50;
        limitOfSbiBank.Maximum_Debit_Allowed_per_Day__c = 30000;
        limitOfSbiBank.Maximum_Transactions_Allowed_per_Day__c = 5;
        limitOfSbiBank.Maximum_Debit_Allowed_per_Transaction__c = 10000;   
        insert limitOfSbiBank;
        
        Contact conObj = new Contact();
        conObj.LastName = 'Testing';
        conObj.email = 'Testing@gmail.com';
        conObj.status__c = 'Active';
        conObj.Transaction_Limit__c = limitOfSbiBank.id;
        insert conObj;
    }
    
    @isTest
    private static void deleteCheck(){
        
        List<Contact> listOfCon = [Select Id From Contact Where LastName = 'Testing'];
        
        Transaction_Entry__c entry = new Transaction_Entry__c();
        entry.Amount__c = 25000;
        entry.Type__c = 'Credit';
        entry.status__c = 'Pending';
        entry.contact__c = listOfCon.get(0).id;
        entry.Transaction_Date__c = System.today();
        insert entry;
        
        test.startTest();
        	RetrieveTransactionEntriesRecords.getEntriesRecord(entry.id, 1);
        test.stopTest();
    }
    
    @isTest
    private static void showRecordWithLimit(){
        
        List<Contact> listOfCon = [Select Id From Contact Where LastName = 'Testing'];
        
        Transaction_Entry__c entry = new Transaction_Entry__c();
        entry.Amount__c = 25000;
        entry.Type__c = 'Credit';
        entry.status__c = 'Pending';
        entry.contact__c = listOfCon.get(0).id;
        entry.Transaction_Date__c = System.today();
        insert entry;
        
        test.startTest();
        	RetrieveTransactionEntriesRecords.getEntriesRecord(entry.id, 1);
        test.stopTest();
    }
    
     @isTest
    private static void showRecordWithDate(){
        
        List<Contact> listOfCon = [Select Id From Contact Where LastName = 'Testing'];        
        Transaction_Entry__c entry = new Transaction_Entry__c();
        entry.Amount__c = 25000;
        entry.Type__c = 'Credit';
        entry.status__c = 'Pending';
        entry.contact__c = listOfCon.get(0).id;
        entry.Transaction_Date__c = System.today();
        insert entry;
        
        Date x = Date.valueOf('2022-12-31');
        Date y = Date.valueOf('2020-12-31');
        test.startTest();
        	RetrieveTransactionEntriesRecords.getEntriesRecordForStatement(entry.id, x , entry.Transaction_Date__c);
        	RetrieveTransactionEntriesRecords.getEntriesRecordForStatement(entry.id, y , entry.Transaction_Date__c);
        test.stopTest();
    }  
}