src/Major Assignment/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <displayFormat>AccNo-{00000}</displayFormat>
        <label>Account Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Available_Balance__c</fullName>
        <label>Available Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Major Assignment/objects/Transaction_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transaction Entries</relationshipLabel>
        <relationshipName>Transaction_Entries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Debit</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction Entry</label>
    <nameField>
        <displayFormat>TX-{00000}</displayFormat>
        <label>TX Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Major Assignment/classes/EmailOfTransactionEntriesRecord.cls
/**
*  Description     :  Send the record on owner email, last day of the months
*                     
*  Created By      :  Jay Chand Yadav
*
*  Created Date    :  09/15/2022
*
*  Revision Logs   :  V1.0 - Created - jay Chand Yadav
**/
global class EmailOfTransactionEntriesRecord implements Schedulable  {
	
    global void execute(SchedulableContext ctx){
        
        Integer mnth = System.Today().Month();

        // Collection of contact ids which is used in transaction entry
        Set<Id> setOfConId = new Set<Id>();
        // Map store contact ia as a id and store Entry record as a value
        Map<Id, List<Transaction_Entry__c>> mapOfTransactionEntry = new Map<Id, List<Transaction_Entry__c>>();

        for(Transaction_Entry__c transEntry: [
		SELECT Id, Type__c, Amount__c, Contact__c, Transaction_Date__c FROM Transaction_Entry__c
		WHERE CALENDAR_MONTH(Transaction_Date__c) =: mnth
		AND status__c = 'Completed']){
            
            setOfConId.add(transEntry.contact__c);

            if(mapOfTransactionEntry.containsKey(transEntry.contact__c)){
                mapOfTransactionEntry.get(transEntry.contact__c).add(transEntry);
            }
            else{
                mapOfTransactionEntry.put(transEntry.contact__c, new List<Transaction_Entry__c>{transEntry});
            }
        }
		System.debug('mapOfTransactionEntry ============> ' + mapOfTransactionEntry);
        for(Contact con: [SELECT Id, Account_Number__c,OwnerId, Available_Balance__c FROM Contact WHERE status__c = 'Active' AND Id IN: setOfConId]){
            List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();        
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            List<String> sendTo = new List<String>();
            sendTo.add(con.OwnerId);
            mail.setToAddresses(sendTo);
            mail.setSubject('Account Details ');
            String body = '';
            body = '<table border="1" style="border-collapse: collapse"><caption style="font-weight:bold;text-align: left;">Transaction Detail:<br/><br/></caption><tr><th>Account number</th><th>Type</th><th>Amount</th><th>Date</th></tr>';
            
            for(Transaction_Entry__c thisMonthEntryRecord: mapOfTransactionEntry.get(con.id)){
		body += '<tr><td>'+ '&nbsp;' + con.Account_Number__c + '&nbsp;'  +'</td><td>' + '&nbsp;' + thisMonthEntryRecord.type__c + '&nbsp;' + '</td><td>' +  '&nbsp;&nbsp;' + thisMonthEntryRecord.Amount__c + '&nbsp;' +'</td><td>'+ '&nbsp;' + thisMonthEntryRecord.Transaction_Date__c + '&nbsp;'  + '</td></tr>';
            }
            
            body += '</table>';
            String body1 = '';
            body1 = '<br/> Available Balance: ' + con.Available_Balance__c;
            body += body1;
            mail.setHtmlBody(body);
            mails.add(mail);       
            Messaging.sendEmail(mails); 
        }
        
        //YourScheduleApexClass s=new YourScheduleApexClass();
		//s.excute(null) ;
    }
}