src/Major Assignment/objects/Transaction_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transaction Entries</relationshipLabel>
        <relationshipName>Transaction_Entries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Debit</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction Entry</label>
    <nameField>
        <displayFormat>TX-{00000}</displayFormat>
        <label>TX Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Major Assignment/classes/RetrieveTransactionEntriesRecords.cls
/**
*  Description     :  Showing the results as per user input and download the documentation (CSV) 
*                     file
*  Created By      :  Jay Chand Yadav
*
*  Created Date    :  09/15/2022
*
*  Revision Logs   :  V1.0 - Created - jay Chand Yadav
**/
public with sharing class RetrieveTransactionEntriesRecords {
    // Shoiwng entries records as the users requirements
    @AuraEnabled(cacheable=true)
    public static List<Transaction_Entry__c> getEntriesRecord(Id recordId, Integer transLimit){

        return [SELECT Id, Name, Amount__c, Type__c, Transaction_Date__c FROM Transaction_Entry__c WHERE Contact__c =: recordId  Limit: transLimit];
    }

    // Fetch the records for (CSV) file 
    @AuraEnabled(cacheable=true)
    public static List<Transaction_Entry__c> getEntriesRecordForStatement(Id recordId, Date start_Date, Date end_Date){

        
        List<Transaction_Entry__c> listOfEntriesRecord = new List<Transaction_Entry__c>();

        Integer dt1 = (start_Date). daysBetween(end_Date);
        System.debug('=================>  Days ===============> ' + dt1);

        try{
            if(182 >= dt1){
                listOfEntriesRecord = [SELECT Id, Name, Amount__c, Type__c, Transaction_Date__c FROM Transaction_Entry__c WHERE Contact__c =: recordId  AND Transaction_Date__c >= :start_Date AND Transaction_Date__c <=: end_Date];
            }
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
        return listOfEntriesRecord;
    }
}